---
name: Checks

on: [push]
jobs:
    checks:
        name: Lint and Test
        runs-on: ubuntu-20.04
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.9'
          - name: Lint
            run: make lint
          - name: Test
            run: make test
